[package]
authors = ["vpzom"]
name = "rustgametest"
version = "0.1.0"

[dependencies]
piston = "0.35.0"
piston2d-graphics = "0.23.0"
piston2d-opengl_graphics = "0.49.0"
pistoncore-sdl2_window = "0.46.0"
